export interface StoryTheme {
  value: string;
  label: string;
  emoji: string;
}

export const storyThemes: StoryTheme[] = [
  { value: "space", label: "Uzay Macerası", emoji: "🚀" },
  { value: "magic", label: "Sihirli Dünya", emoji: "✨" },
  { value: "mermaid", label: "Denizkızı Masalı", emoji: "🧜‍♀️" },
  { value: "pirates", label: "Korsan Hazinesi", emoji: "⚓" },
  { value: "forest", label: "Sihirli Orman", emoji: "🌳" },
  { value: "dinosaurs", label: "Dinozorlar Diyarı", emoji: "🦖" },
  { value: "dragons", label: "Ejderha Dostluğu", emoji: "🐉" },
  { value: "fairies", label: "Peri Krallığı", emoji: "🧚‍♀️" },
  { value: "circus", label: "Sirk Macerası", emoji: "🎪" },
  { value: "zoo", label: "Hayvanat Bahçesi", emoji: "🦁" },
  { value: "castle", label: "Şato Gizemi", emoji: "🏰" },
  { value: "underwater", label: "Denizaltı Keşfi", emoji: "🌊" },
  { value: "jungle", label: "Orman Krallığı", emoji: "🦒" },
  { value: "arctic", label: "Kutup Macerası", emoji: "❄️" },
  { value: "desert", label: "Çöl Hazinesi", emoji: "🐪" },
  { value: "farm", label: "Çiftlik Hayatı", emoji: "🚜" },
  { value: "school", label: "Okul Macerası", emoji: "📚" },
  { value: "superheroes", label: "Süper Kahramanlar", emoji: "🦸‍♂️" },
  { value: "robots", label: "Robot Dostlar", emoji: "🤖" },
  { value: "time_travel", label: "Zaman Yolculuğu", emoji: "⏰" },
  { value: "space", label: "Uzay Macerası" },
  { value: "magic", label: "Sihirli Dünya" },
  { value: "mermaid", label: "Denizkızı Masalı" },
  { value: "pirates", label: "Korsan Hazinesi" },
  { value: "forest", label: "Sihirli Orman" },
  { value: "dinosaurs", label: "Dinozorlar Diyarı" },
  { value: "dragons", label: "Ejderha Dostluğu" },
  { value: "fairies", label: "Peri Krallığı" },
  { value: "circus", label: "Sirk Macerası" },
  { value: "zoo", label: "Hayvanat Bahçesi" },
  { value: "castle", label: "Şato Gizemi" },
  { value: "underwater", label: "Denizaltı Keşfi" },
  { value: "jungle", label: "Orman Krallığı" },
  { value: "arctic", label: "Kutup Macerası" },
  { value: "desert", label: "Çöl Hazinesi" },
  { value: "farm", label: "Çiftlik Hayatı" },
  { value: "school", label: "Okul Macerası" },
  { value: "superheroes", label: "Süper Kahramanlar" },
  { value: "robots", label: "Robot Dostlar" },
  { value: "time_travel", label: "Zaman Yolculuğu" },
  { value: "candy_land", label: "Şeker Diyarı" },
  { value: "toys", label: "Oyuncak Dünyası" },
  { value: "rainbow", label: "Gökkuşağı Ülkesi" },
  { value: "clouds", label: "Bulut Şehri" },
  { value: "music", label: "Müzik Adası" },
  { value: "sports", label: "Spor Festivali" },
  { value: "seasons", label: "Mevsimler Ülkesi" },
  { value: "garden", label: "Sihirli Bahçe" },
  { value: "beach", label: "Plaj Macerası" },
  { value: "surprise", label: "Sürpriz (Yapay Zekaya Bırak)" },
]; 